import os
import pandas as pd
from snakemake.utils import validate


# Set your specific experimental configuration here
configfile: "config/test.yaml"


# Include rules from other files
# include: "rules/checkpoint.smk"
include: "rules/common.smk"
include: "rules/all.smk"


# include: "rules/cluster_barcodes.smk"
# include: "rules/consensus.smk"
# include: "rules/mapping.smk"
# include: "rules/ref.smk"


# Pseudo-rule for running analysis
rule all_2:
    input:
        get_input,
