# Configuration for DMS analysis
# This file is validated against the schema in "schemas/config.schema.yaml"

# This is the name of the experiment. This is used to name the output files and 
# results directories, so it must be unique.
experiment: 'test_data'

# -----------------------------------------------------------------------------
# Path definitions:
# These paths are relative to the base snakemake invocation directory,
# typically the root of the git repository. 
# data_dir: Directory containing the raw sequencing data. Note: _all_ reads
#           are expected in this directory, not as subfolders!
# ref_dir: Directory containing the reference fasta files.
# -----------------------------------------------------------------------------

data_dir: 'test/data'
ref_dir: 'references'

# -----------------------------------------------------------------------------
# File definitions:
# These files are relative to the base snakemake invocation directory, as well.
# experiment_file: CSV file containing the experiment metadata for describing
#                  the experiment structure and the mapping to each file.
#                  This file must contain the following columns:
#                     sample: Unique sample name
#                     file: File name.
#
#                   This file is validated against the schema in "schemas/experiments.schema.yaml"
#
# reference: Reference fasta file name. This must be a nucleotide fasta file!
# -----------------------------------------------------------------------------
experiment_file: 'config/test.csv'
reference: test.fasta

# -----------------------------------------------------------------------------
# Analysis parameters:
#
# orf: The coordinate range of the ORF within the reference file.
#
# flanking_sequence: Flanking constant nucleotide sequence around barcode.
#                    In format "GCTGTACGTA...GGTACATTTG" where "..." is the barcode sequence.
# ----------------------------------------------------------------------------- 
flanking_sequence: "GCAGTCTGGTGTATGCCTAC...GGTACATTTGAACGCCAAGG"
orf: "141-1568"

# -----------------------------------------------------------------------------
# Other parameters:
#
#
# kmers: The kmer length to use for BBMap jobs.
#
# sam: The SAM format version to use for BBMap jobs. This should be "1.3" for most cases.
#
# mem: Memory to allocate for BBMap jobs with Java (in GB)
#
# min_q: Used in GATK: the minimum quality score for bases to be analyzed. 
#
# -----------------------------------------------------------------------------

